cat("-------------------------------- LDA ---------------------------------",sep="\n\n")
library(MASS)
model_lda <- lda(IsAlert~., data=TRAIN)
predicted_lda <- predict(model_lda, newdata = TEST)
tbl <- table(pred=predicted_lda$class,actual=TEST$IsAlert)
print(tbl)
cat(paste("Accuracy on LDA:",sum(diag(tbl))/length(VALIDATION_SET)),sep="\n")
cat("\n")
