cat("-------------------------------- LDA ---------------------------------",sep="\n\n")
library(MASS)
model_lda <- lda(IsAlert~., data=TRAIN)
predicted_lda <- predict(model_lda, newdata = TEST)
tbl <- table(pred=predicted_lda$class,actual=TEST$IsAlert)
print(tbl)
cat(paste("Accuracy on LDA:",mean(tbl[1,1]/sum(tbl[,1]),tbl[2,2]/sum(tbl[,2])), sep="\n"))
cat("\n")