cat("Principal Component Analysis")
cat("\n")
names(fordTrain)
pc <- prcomp(TEST[,-c(1)],center = F, scale = F)
print(pc)
summary(pc)
plot(pc,type="l")

prc <- princomp(TEST[,-c(1)])
plot(prc)
print(prc)
summary(prc)
loadings(prc)
varImpPlot(model_rf)
